lst1 = ['diksha/table_reports/all/2401.json', 'diksha/table_reports/all/2402.json',
        'diksha/table_reports/all/2403.json', 'diksha/table_reports/all/2404.json',
        'diksha/table_reports/all/2405.json', 'diksha/table_reports/all/2406.json',
        'diksha/table_reports/all/2407.json', 'diksha/table_reports/all/2408.json',
        'diksha/table_reports/all/2409.json', 'diksha/table_reports/all/2410.json',
        'diksha/table_reports/all/2411.json', 'diksha/table_reports/all/2412.json',
        'diksha/table_reports/all/2413.json', 'diksha/table_reports/all/2414.json',
        'diksha/table_reports/all/2415.json', 'diksha/table_reports/all/2416.json',
        'diksha/table_reports/all/2417.json', 'diksha/table_reports/all/2418.json',
        'diksha/table_reports/all/2419.json', 'diksha/table_reports/all/2420.json',
        'diksha/table_reports/all/2421.json', 'diksha/table_reports/all/2422.json',
        'diksha/table_reports/all/2423.json', 'diksha/table_reports/all/2424.json',
        'diksha/table_reports/all/2425.json', 'diksha/table_reports/all/2426.json',
        'diksha/table_reports/all/2427.json', 'diksha/table_reports/all/2428.json',
        'diksha/table_reports/all/2429.json', 'diksha/table_reports/all/2430.json',
        'diksha/table_reports/all/2431.json', 'diksha/table_reports/all/2432.json',
        'diksha/table_reports/all/2433.json', 'diksha/table_reports/all/All.json']
lst2 = ['diksha/table_reports/all/2401.json', 'diksha/table_reports/all/2402.json',
        'diksha/table_reports/all/2403.json', 'diksha/table_reports/all/2404.json',
        'diksha/table_reports/all/2405.json', 'diksha/table_reports/all/2406.json',
        'diksha/table_reports/all/2407.json', 'diksha/table_reports/all/2408.json',
        'diksha/table_reports/all/2409.json', 'diksha/table_reports/all/2410.json',
        'diksha/table_reports/all/2411.json', 'diksha/table_reports/all/2412.json',
        'diksha/table_reports/all/2413.json', 'diksha/table_reports/all/2414.json',
        'diksha/table_reports/all/2415.json', 'diksha/table_reports/all/2416.json',
        'diksha/table_reports/all/2418.json', 'diksha/table_reports/all/2419.json',
        'diksha/table_reports/all/2420.json', 'diksha/table_reports/all/2421.json',
        'diksha/table_reports/all/2422.json', 'diksha/table_reports/all/2423.json',
        'diksha/table_reports/all/2424.json', 'diksha/table_reports/all/2425.json',
        'diksha/table_reports/all/2426.json', 'diksha/table_reports/all/2427.json',
        'diksha/table_reports/all/2428.json', 'diksha/table_reports/all/2429.json',
        'diksha/table_reports/all/2430.json', 'diksha/table_reports/all/2431.json',
        'diksha/table_reports/all/2432.json', 'diksha/table_reports/all/2433.json', 'diksha/table_reports/all/All.json']
if lst1 == lst2:
    print("same")
else:
    print("not same")